---
title: "Bagerstop 2021"
author: "Jeppe Dreyer Matzen"
date: "3/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require("tidyverse")) install.packages("tidyverse")
library(tidyverse)
if (!require("scales")) install.packages("scales")
library(scales)
if (!require("lubridate")) install.packages("lubridate")
library(lubridate)
if (!require("forecast")) install.packages("forecast")
library(forecast)
if (!require("gganimate")) install.packages("gganimate")
library(gganimate)
if (!require("hms")) install.packages("hms")
library(hms)
library(png)
library(gifski)
library(magick)
```

# Data cleaning
```{r}
pre_navn =c('Jeppe M','Ditte F', 'Søb', 'Filtenborg', 'Frederik','Kim P', 'Swag', "Nikoline",'Tank', 'Lasse N', 'Jeppe C', 'Claes', 'Bastian', 'Alex')
pre_navn2 =c('Jeppe M','Ditte F', 'Søb', 'Filtenborg', 'Frederik','Kim P', 'Swag', "Nikoline",'Tank', 'Lasse N', 'Jeppe C', 'Claes', 'Bastian', 'Alex')#13

pre_dato = c("2021-02-28", "2021-02-28","2021-02-28","2021-02-28","2021-02-28","2021-02-28","2021-02-28","2021-02-28","2021-02-28","2021-02-28","2021-02-28","2021-02-28", "2021-02-28","2021-02-28")
pre_dato2 = as.Date(c(Sys.Date(),Sys.Date(),Sys.Date(),Sys.Date(),Sys.Date(),Sys.Date(),Sys.Date(),Sys.Date(),Sys.Date(),Sys.Date(),Sys.Date(), Sys.Date(), Sys.Date(),Sys.Date()))

pre_distance =c(0,0,0,0,0,0,0,0,0,0,0, 0,0,0)
pre_distamce2 =c(0,0,0,0,0,0,0,0,0,0,0, 0,0,0)

pre_tid = lubridate::hms(c("00:00:00", "00:00:00", "00:00:00", "00:00:00", "00:00:00", "00:00:00", "00:00:00", "00:00:00", "00:00:00", "00:00:00", "00:00:00","00:00:00","00:00:00","00:00:00"))
pre_tid2 = lubridate::hms(c("00:00:00", "00:00:00", "00:00:00", "00:00:00", "00:00:00", "00:00:00", "00:00:00", "00:00:00", "00:00:00", "00:00:00", "00:00:00","00:00:00","00:00:00","00:00:00"))

pre_kage =c(0,0,0,0,0,0,0,0,0,0,0,0,0,0)
pre_kage2 =c(0,0,0,0,0,0,0,0,0,0,0,0,0,0)

pre_point= c(0,0,0,0,0,0,0,0,0,0,0,0,0,0)
pre_point2= c(0,0,0,0,0,0,0,0,0,0,0,0,0,0)

pre_type= c('NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA', 'NA', 'NA', 'NA')
pre_type2= c('NA','NA','NA','NA','NA','NA','NA','NA','NA','NA','NA', 'NA', 'NA' ,'NA')

pre_data = data.frame(navn =pre_navn, dato=as_date(pre_dato), distance=pre_distance, tid=pre_tid, type=pre_type, kage=pre_kage, point=pre_point)

pre_data2 = data.frame(navn =pre_navn2, dato=as_date(pre_dato2), distance=pre_distamce2, tid=pre_tid2, type=pre_type2, kage=pre_kage2, point=pre_point2)

# # # # # # # # # # # # # # # # # # # # # # # # #
navn <- c('Jeppe M','Ditte F', 'Søb', 'Filtenborg', 'Frederik', 'Jeppe M', 'Kim P', 'Filtenborg', 'Jeppe C', 'Frederik', 'Swag', "Nikoline", 'Jeppe M', 'Tank', 'Lasse N', 'Swag', 'Frederik', 'Frederik', 'Ditte F', 'Nikoline', 'Ditte F', 'Claes', 'Filtenborg', 'Søb', 'Frederik', 'Frederik', 'Filtenborg', 'Ditte F', 'Bastian', 'Alex', 'Frederik', 'Swag', 'Søb', 'Filtenborg', 'Nikoline', 'Jeppe M')

dato <- as.Date(c("2021-03-01", "2021-03-01", "2021-03-01", "2021-03-01", "2021-03-01", "2021-03-02", "2021-03-02", "2021-03-02", "2021-03-02", "2021-03-02", "2021-03-02", "2021-03-02", "2021-03-03", "2021-03-03", "2021-03-03", "2021-03-03", "2021-03-03","2021-03-04", "2021-03-04", "2021-03-04", "2021-03-05", "2021-03-05", "2021-03-05", "2021-03-05", "2021-03-05", "2021-03-06", "2021-03-06", "2021-03-06", "2021-03-07", "2021-03-07", "2021-03-07", "2021-03-07", "2021-03-07", "2021-03-07", "2021-03-07", "2021-03-08"))

distance <- c(56.86, 52.62, 51.25, 82.0, 80.2, 56.61,80.3,  53.3, 51.27, 80.0, 51.6, 80.22, 53.1, 50, 50, 50, 80.5, 80.2, 51.21, 51.6, 50.54, 80, 41.4, 41.4,80.2, 161, 50.4, 50.06, 117.4, 50, 161, 51.3, 32.53, 32.53, 50, 46.03)

tid <- lubridate::hms(c("02:22:22", "03:00:00", "02:57:16", "03:06:17", "02:39:35", "02:26:08", "02:40:30", "02:28:27", "02:46:00", "02:38:08", "02:35:00", "02:57:02", "02:19:46", "03:30:00", "03:30:00", "02:43:00", "02:35:38", "02:41:31", "03:00:00", "02:38:10", "03:00:00", "03:40:00", "03:04:05", "03:04:05", "02:32:11", "05:38:48", "02:33:42", "03:05:25", "03:52:09", "03:00:00", "05:30:01", "03:07:00", "03:00:00", "03:00:00", "03:02:44", "01:58:58"))

type <- c("mtb", "mtb", "mtb", "landevej", "landevej", "mtb", "landevej", "mtb", "mtb", "landevej", "mtb", "mtb", "mtb", "mtb", "mtb", "landevej", "landevej", "landevej", "mtb", "mtb", "mtb", "landevej", "mtb", "mtb", "landevej", "landevej", "mtb", "mtb", "landevej", "mtb", "landevej", "mtb", "mtb", "mtb", "mtb","mtb")

kage <- c(0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,0, 0, 0, 0, 1, 1, 1,2, 0, 0, 0,0,2,0, 1, 1, 1, 0 )

point <- c(1, 1, 1, 1,  1, 1.3, 1, 1, 1, 1, 1, 1.3, 1.8, 1.3, 1.3, 1.3, 1.5, 1, 1, 1, 1, 1, 1.3, 1.3, 1, 2.5, 1, 1, 1.3, 1, 2, 1.3, 1.3, 1.8, 1.3, 1)

data <- data.frame(navn, dato=as_date(dato), distance, tid, type, kage, point)

data_samlet <- rbind(pre_data, data, pre_data2 )


```

# Tilføjelse af 0
```{r}
# data_samlet <- data_samlet %>% 
#     group_by(navn) %>% 
#     complete(dato = seq.Date(min(dato), max(dato), by="day"), distance) 
```


# Data Summary
```{r}
# data_kim <- data %>% 
#     arrange(dato) %>% 
#     group_by(navn) %>% 
#     mutate(Samlet_point = cumsum(point))
# write.csv(x=data_kim, file="data_kim")
```


```{r}
data_samlet %>% 
    filter(!is.na(type)) %>% 
    group_by(navn) %>%
    unique() %>% 
    summarise(Antal_ture = n()-2,
              Samlet_distance = sum(distance),
              Samlet_Time = seconds_to_period(sum(as.numeric(tid))),
              Antal_kager = sum(kage),
              Samlet_distance = sum(distance),
              Point = sum(point)) %>% 
    arrange(desc(Point)) %>% 
    knitr::kable()

```
# Normal plots
```{r}
library(ggrepel)
modified_data <- data_samlet %>%
    group_by(navn) %>%
    unique() %>% 
    arrange(dato) %>% 
    mutate(samlet_distance = cumsum(distance),
           samlet_point = cumsum(point),
           samlet_tid = seconds_to_period(cumsum(as.numeric(tid))))

d <- modified_data %>% 
ggplot(aes(x = dato, y = samlet_distance,color = navn, group = navn)) +
    geom_step()+
    geom_label_repel(data = subset(modified_data, dato==max(dato)), 
                     aes(label=navn), nudge_x =0.1, max.overlaps = 20)+
    scale_x_date(date_labels = "%b %d", date_minor_breaks = "1 day")+ 
    labs(title = "Samlet Km i bagerstop konkurrencen",
         x = "",
         y = "Kilometer")


t <- modified_data %>% 
ggplot(aes(x = dato, y = samlet_tid,color = navn, group = navn)) +
    geom_step()+
    geom_point()+
    geom_label_repel(data = subset(modified_data, dato==max(dato)), 
                     aes(label=navn), nudge_x=0.1, max.overlaps = 20)+
    scale_x_date(date_labels = "%b %d", date_minor_breaks = "1 day")+
    scale_y_time()+ 
    labs(title = "Samlet Tid i bagerstop konkurrencen",
         x = "")

p <- modified_data %>% 
ggplot(aes(x = dato, y = samlet_point,color = navn, group = navn)) +
    geom_step()+
    geom_point() +
    geom_label_repel(data = subset(modified_data, dato==max(dato)), 
                     aes(label=navn), nudge_x=0.1, max.overlaps = 20)+
    scale_x_date(date_labels = "%b %d", date_minor_breaks = "1 day") + 
    labs(title = "Samlet Point i bagerstop konkurrencen",
         x = "",
         y = "Point")
plot(d)
```

# Create animated plot
```{r}
animate_d <-ggplot(modified_data, aes(as.Date(dato), samlet_distance, color = navn, group = navn)) + 
  geom_step()+
  geom_segment(aes(xend = Sys.Date()+1, yend = samlet_distance), linetype = 2, colour = 'grey') + 
  geom_point(size = 2) + 
  geom_text_repel(aes(x = Sys.Date(), label = navn), hjust = 0.1) + 
  transition_reveal(as.Date(dato)) + 
  coord_cartesian(clip = 'off') + 
  labs(title = 'Samlet distance i Bagerstop konkurrencen 2021', y = 'Km kørt', x = "") + 
  theme_minimal() + 
  theme(plot.margin = margin(5.5, 40, 5.5, 5.5))

animate_t <-ggplot(modified_data, aes(as.Date(dato), samlet_tid, color = navn, group = navn)) + 
  geom_step()+
  geom_segment(aes(xend = Sys.Date()+1, yend = samlet_tid), linetype = 2, colour = 'grey') + 
  geom_point(size = 2) + 
  geom_text_repel(aes(x = Sys.Date(), label = navn)) + 
  transition_reveal(as.Date(dato)) + 
  coord_cartesian(clip = 'off') + 
  labs(title = 'Samlet tid i Bagerstop konkurrencen 2021', y = 'Tid kørt', x= "") + 
  theme_minimal() + 
  theme(plot.margin = margin(5.5, 40, 5.5, 5.5))

animate_p <-ggplot(modified_data, aes(as.Date(dato), samlet_point, color = navn, group = navn)) + 
  geom_step()+
  geom_segment(aes(xend = Sys.Date()+1, yend = samlet_point), linetype = 2, colour = 'grey') + 
  geom_point(size = 2) + 
  geom_text_repel(aes(x = Sys.Date(), label = navn)) + 
  transition_reveal(as.Date(dato)) + 
  coord_cartesian(clip = 'off') + 
  labs(title = 'Samlet point i Bagerstop konkurrencen 2021', y = 'Point', x = "") + 
  theme_minimal() + 
  theme(plot.margin = margin(5.5, 40, 5.5, 5.5))
```


# Compile and show animation
```{r}
image1 <- animate(animate_d, fps=5, width = 700, height = 400, end_pause=15)
image2 <- animate(animate_t, fps=5, width = 700, height = 400, end_pause=15)
image3 <- animate(animate_p, fps=5, width = 700, height = 400, end_pause=15)
```


